generate_docs
generate_docs.check_doxygen_installed()
Check if Doxygen is installed on the system.
Referenced by main.
generate_docs.check_graphviz_installed()
Check if Graphviz is installed (needed for diagram generation).
Referenced by main.
generate_docs.generate_documentation()
Run Doxygen to generate documentation.
Referenced by main.
generate_docs.open_documentation()
Open the generated documentation in default browser.
Referenced by main.
generate_docs.main()
Main function to orchestrate documentation generation.
References check_doxygen_installed, check_graphviz_installed, generate_documentation, main, open_documentation.
Referenced by main.