model
model.spark
model.df_all
str model.DB_PATH
str model.CSV_PATH
model.extract_cast_names(cc_str)
Extract cast members from pipe-separated cast string. Parses cast_and_crew format: "FirstName|LastName,FirstName|LastName,..." Returns a set of lowercase "firstname lastname" pairs for easy comparison. Args: cc_str (str): Cast string in format "First|Last,First|Last,..." Returns: set: Set of lowercased "firstname lastname" pairs Example: >>> extract_cast_names("Tom|Hanks,Tim|Allen") {'tom hanks', 'tim allen'}
Referenced by get_recommendations_for_last_added, get_top_recommendations, read_csv.
model.extract_base_title(title)
Extract base franchise name from movie title. Removes franchise indicators like "Part 2", "Returns", "Sequel", etc. to identify movies from the same franchise. Args: title (str): Movie title string Returns: str: Lowercased base title without franchise indicators Example: >>> extract_base_title("Toy Story 2: The Sequel") 'toy story'
Referenced by franchise_similarity, read_csv.
model.genre_similarity(user_genres, movie_genres)
Calculate Jaccard similarity between user's genres and movie's genres. Jaccard similarity = |intersection| / |union| Ranges from 0.0 (no overlap) to 1.0 (identical genres) Args: user_genres (str): Pipe-separated genre string from user profile movie_genres (str): Pipe-separated genre string from candidate movie Returns: float: Jaccard similarity score [0.0, 1.0]
model.franchise_similarity(user_title, movie_title)
Check if two movies belong to the same franchise. Uses extract_base_title to compare base franchise names. Args: user_title (str): Title of user's rated movie movie_title (str): Title of candidate movie Returns: float: 1.0 if same franchise, 0.0 otherwise
References extract_base_title.
Referenced by get_recommendations_for_last_added, get_top_recommendations.
model.cast_similarity(user_names_str, movie_names_str)
Calculate cast overlap as a ratio of common actors. Compares pre-extracted cast names. Returns ratio of overlapping actors to total actors in the candidate movie. Args: user_names_str (str): Pipe-separated cast names from user's movies movie_names_str (str): Pipe-separated cast names from candidate movie Returns: float: Ratio [0.0, 1.0] of movie actors present in user's cast
model.read_csv()
Load and preprocess CSV data into Spark DataFrame. Performs the following operations: 1. Reads CSV with proper escape/quote handling for complex fields 2. Extracts cast names from cast_and_crew field 3. Pre-computes base titles for franchise matching 4. Splits genres and cast into arrays for efficient Spark operations 5. Cleans and casts numeric columns 6. Caches result for reuse Returns: DataFrame: Cached Spark DataFrame with preprocessed movie data Global: df_all: Set to the loaded and cached DataFrame
References extract_base_title, extract_cast_names.
Referenced by create_spark_and_load_data.
model.create_spark_and_load_data()
Initialize Spark session and load/preprocess CSV data. Creates local Spark session with optimized settings for movie recommendations: - Uses all available CPU cores - Minimizes shuffle partitions for faster processing - Configures driver for stable operation Global: spark: Initialized SparkSession instance
References read_csv.
Referenced by get_recommendations_by_most_common_genre, get_recommendations_for_last_added, get_top_recommendations.
model.get_top_recommendations(user_id, top_n=10)
Generate personalized recommendations for a user. Algorithm: 1. Loads user's rated movies from SQLite 2. Builds weighted user profile combining genres, cast, and ratings 3. Filters out user's already-rated movies 4. Calculates similarity scores for remaining movies: - Genre similarity (45% weight) - Cast similarity (15% weight) - Franchise similarity (5% weight) - User's average rating norm (35% weight) 5. Returns top N movies by hybrid score Args: user_id (int): Database user ID top_n (int): Number of recommendations to return (default 10) Returns: list: List of dicts with keys: - title: Movie title - cast_names: Pipe-separated cast string - genre_sim, cast_sim, franchise_sim: Individual similarity scores - user_rating_norm: User's average rating - hybrid_score: Combined score [0.0, 1.0] - cast_overlap: List of cast members in both user profile and movie
References create_spark_and_load_data, extract_cast_names, franchise_similarity.
model.get_recommendations_for_last_added(user_id, top_n=10)
Generate recommendations based on user's most recently added movie. Algorithm: 1. Retrieves user's last added movie from SQLite 2. Finds similar movies by comparing: - Genres (45% weight) - Cast members (15% weight) - Franchise (5% weight) - Average rating (35% weight) 3. Returns top N similar movies Args: user_id (int): Database user ID top_n (int): Number of recommendations to return (default 10) Returns: list: List of dicts with keys: - title: Movie title - genres: Pipe-separated genre string - cast_names: Pipe-separated cast string - genre_sim, cast_sim, franchise_sim: Individual similarity scores - hybrid_score: Combined score - reference_movie: Title of the movie used as basis - cast_overlap: List of shared cast members
References create_spark_and_load_data, extract_cast_names, franchise_similarity.
model.get_recommendations_by_most_common_genre(user_id, top_n=10)
Generate recommendations based on user's most frequently watched genre. Algorithm: 1. Identifies the most common genre in user's rated movies 2. Filters movies containing that genre 3. Scores movies using: - Genre match (70% weight) - 1.0 if contains main genre, 0.0 otherwise - Average rating (30% weight) 4. Returns top N movies by combined score Args: user_id (int): Database user ID top_n (int): Number of recommendations to return (default 10) Returns: list: List of dicts with keys: - title: Movie title - genres: Pipe-separated genre string - avg_rating: Movie's average rating - genre_match: 1.0 if contains main genre, 0.0 otherwise - score: Combined score [0.0, 1.0]
References create_spark_and_load_data.